Controllers/AnasayfaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChessProject.Models.Entitiy;
namespace ChessProject.Controllers
{
    public class AnasayfaController : Controller
    {
        ChessEntities db = new ChessEntities();
        public ActionResult Home()
        {//ANA SAYFADAKİ VERİLERİ ÇEKİYORUM
            try
            {
                Homelist ls = new Homelist();
                ls.blog = db.Tbl_Blog.OrderByDescending(x => x.ID).Take(3).ToList();
                ls.home = db.Tbl_Home.ToList();
                ls.comment = db.Tbl_Comment.OrderByDescending(x => x.ID).Where(x=>x.CommentOkay==true).Take(3).ToList();
                return View(ls);
            }
            catch (Exception a)
            {
                Response.Write("<script lang='JavaScript'>alert('" + a.Message + "');</script>");
                return View();
            }

        }
        public PartialViewResult Layoutwett()
        {  //LAYOUTTAKİ TWETTLERİ ÇEKİYOR
            try
            {
                var deger = db.TblDetay.OrderByDescending(x => x.ID).Take(3).ToList();
                return PartialView(deger);
            }
            catch (Exception a)
            {
                Response.Write("<script lang='JavaScript'>alert('" + a.Message + "');</script>");
                return PartialView();
            }
        }
        public PartialViewResult InfoInsterting()
        {  // İLGİNÇ BİLGİLERDEN 2 TANE VERİ ÇEKİYORUZ
            try
            {
                var deger = db.Tbl_InterestingInfo.OrderByDescending(x => x.ID).Take(2).ToList();
                return PartialView(deger);
            }
            catch (Exception a)
            {
                Response.Write("<script lang='JavaScript'>alert('" + a.Message + "');</script>");
                return PartialView();
            }
        }
    }
}

Views/Shared/Layout.cshtml
@{
    Layout = null;
}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>KRALLARIN OYUNU</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/web/css/bootstrap.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Kreon:300,400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700,800' rel='stylesheet' type='text/css'>
    <link href="~/web/css/style.css" rel="stylesheet">
</head>
<body>
    <header class="main__header">
        <div class="container">
            <nav class="navbar navbar-default" role="navigation">
                <div class="navbar-header"> <a href="#" onClick="javascript.void()" class="submenu">Menus</a> </div>
                <div class="menuBar">
                    <ul class="menu">
                        <li class="active"><a href="~/Anasayfa/Home/">ANA SAYFA</a></li>
                        <li class="dropdown">
                            <a href="#">BİLGİLER</a>
                            <ul>
                                <li><a href="~/Satranc/Nedir">SATRANÇ NEDİR ?</a></li>
                                <li><a href="~/Blog/Sayfa">BLOG</a></li>
                                <li><a href="~/Ilgınc/Liste/">İLGİNÇ BİLGİLER</a></li>
                            </ul>
                        </li>
                        <li><a href="~/Iletisim/iletisim/">İLETİŞİM</a></li>
                        <li><a href="~/Login/GirisYap">GİRİŞ YAP</a></li>
                    </ul>
                </div>
            </nav>
            <div class="navbar-header with__logo">
                <h1 class="navbar-brand"><a href="~/Anasayfa/Home/">SATRANÇ</a></h1>
            </div>
        </div>
    </header>
    @RenderBody()
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h3>Hakkımızda</h3>
                    <div class="seper lefter"></div>
                    <p>
                        Satrançı bir yaşam tarzı yapmış ,bunun bir oyundan daha çok hayatın kendisi olduğunu biliyoruz. <br />
                        <br />
                        Bu web sitemizde size satrancın güzellikleri bu derya denize beraber girip burada beraber düşünmeyi istiyoruz SATRANÇLA KALIN :)
                    </p>
                </div>
                @Html.Action("Layoutwett", "Anasayfa")
                <div class="col-md-3">
                </div>
                <div class="col-md-3">
                    <h3>İletişim Bilgileri</h3>
                    <div class="seper lefter"></div>
                    <p>
                        SILIVRI/ISTANBUL<br />
                        TÜRKİYE<br />
                        <br />
                        Telefon: +90 (544) 289-5650<br />
                        <br />
                    </p>
                    <div class="social__icons"><a href="mailto:ghasab101@gmail.com" class="socialicon socialicon-google"></a></div>

                </div>
            </div>
        </div>
    </footer>
    <p class="text-center copyright">&copy; Copyright TÜM HAKLARI SAKLIDIR 2021 | DESIGN BY DOĞUKAN KOŞAN</p>
</body>
</html>
<script type="text/javascript" src="js/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>
<script type="text/javascript">

    $('.carousel').carousel({
        interval: 3500, // in milliseconds
        pause: 'none' // set to 'true' to pause slider on mouse hover
    })

</script>
<script type="text/javascript">
    $("a.submenu").click(function () {
        $(".menuBar").slideToggle("normal", function () {
            // Animation complete.
        });
    });
    $("ul li.dropdown a").click(function () {
        $("ul li.dropdown ul").slideToggle("normal", function () {
            // Animation complete.
        });
        $('ul li.dropdown').toggleClass('current');
    });
</script>

Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>ADMİN</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href="~/web2/css/bootstrap.css" rel="stylesheet" />
    <link href="~/web2/css/style.css" rel="stylesheet" />

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />

    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>
</head>
<body>
    <div class="w3-sidebar w3-bar-block w3-border-right" style="display:none" id="mySidebar">
        <button onclick="w3_close()" class="w3-bar-item w3-large">Kapat &times;</button>
        <a href="~/AdminHome/AnaSayfaDuzenle/" class="w3-bar-item w3-button">Ana Sayfa</a>
        <a href="~/AdminPanel/AdminAna/" class="w3-bar-item w3-button">Bloglar</a>
        <a href="~/AdminYorum/YorumListe/" class="w3-bar-item w3-button">Yorumlar</a>
        <a href="~/AdminIlginc/Listele/" class="w3-bar-item w3-button">İlginç Bilgiler</a>
        <a href="~/AdminIletisim/IletisimList/" class="w3-bar-item w3-button">İletişim</a>
        <a href="~/Anasayfa/Home/" class="w3-bar-item w3-button">Siteye Git</a>
        <a href="~/Login/Logout/" class="w3-bar-item w3-button">Çıkış Yap</a>
    </div>
    <div class="w3-orange">
        <button class="w3-button w3-orange w3-xlarge" onclick="w3_open()">☰</button>
        <div class="w3-container">
            <h1>ADMİN PANELİ</h1>
        </div>
    </div>
    <div class="w3-container">
        @RenderBody()
    </div>
    <script>
        function w3_open() {
            document.getElementById("mySidebar").style.display = "block";
        }
        function w3_close() {
            document.getElementById("mySidebar").style.display = "none";
        }
    </script>

</body>
</html>