Controllers/AdminPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChessProject.Models.Entitiy;
namespace ChessProject.Controllers
{
    public class AdminPanelController : Controller
    {//MODELİM EF
        ChessEntities db = new ChessEntities();
        [Authorize]
        public ActionResult AdminAna()
        {// BLOG LİSTELEME YAPAR
            try
            {
                var deger = db.Tbl_Blog.ToList();
                return View(deger);
            }
            catch (Exception a)
            {
                Response.Write("<script lang='JavaScript'>alert('" + a.Message + "');</script>");
                return View();
            }
        }
        [Authorize]
        public ActionResult Delete(Int16 id)
        {// BLOG SİLME İŞLEMİ YAPAR
            try
            {
                var deger = db.Tbl_Blog.Find(id);
                db.Tbl_Blog.Remove(deger);
                db.SaveChanges();
                return RedirectToAction("AdminAna");
            }
            catch (Exception a)
            {
                Response.Write("<script lang='JavaScript'>alert('" + a.Message + "');</script>");
                return View("AdminAna");
            }
        }
        [Authorize]
        public ActionResult Add()
        {   //BLOG EKLEME SAYFASINI AÇAR
            return View();
        }
        [Authorize]
        public PartialViewResult BlogDetayAdd()
        {// BLOG EKLEME SAYFASINDA BLOG DETAY TABLOSUNA EKLEMEK İÇİN MODELİ GETİRİR
            return PartialView();
        }
        [Authorize]
        public ActionResult AddGo(Tbl_Blog p, TblDetay k)
        {//BLOG EKLEME İŞLEMİ YAPAR
            try
            {
                k.BlogID = p.ID;
                db.Tbl_Blog.Add(p);
                db.TblDetay.Add(k);
                db.SaveChanges();
                return RedirectToAction("AdminAna");
            }
            catch (Exception a)
            {
                Response.Write("<script lang='JavaScript'>alert('" + a.Message + "');</script>");
                return View("Add");
            }
        }
        [Authorize]
        public ActionResult UpdatePage(Int16 id)
        {//GÜNCELLEME SAYFASINA GİDİŞ
            try
            {
                var deger = db.Tbl_Blog.Find(id);
                TempData["id"] = id;
                return View(deger);
            }
            catch (Exception a)
            {
                Response.Write("<script lang='JavaScript'>alert('" + a.Message + "');</script>");
                return View("AdminAna");
            }
        }
        [Authorize]
        public PartialViewResult BlogDetayUpdate()
        {// BLOG GÜNCELLEME SAYFASINDA BLOG DETAY TABLOSUNu GÜNCELLEMEK İÇİN MODELİ GETİRİR
            try
            {
                Int16 id = Convert.ToInt16(TempData["id"]);
                var deger = db.TblDetay.Where(x => x.BlogID == id).FirstOrDefault();
                return PartialView(deger);
            }
            catch (Exception a)
            {
                Response.Write("<script lang='JavaScript'>alert('" + a.Message + "');</script>");
                return PartialView("AdminAna");
            }
        }
        [Authorize]
        public ActionResult UpdateGo(Tbl_Blog p, TblDetay k)
        {// BLOG GÜNCELLEME
            try
            {
                var blog = db.Tbl_Blog.Find(p.ID);
                blog.BlogTitle = p.BlogTitle;
                blog.BlogComment = p.BlogComment;
                blog.BlogImage = p.BlogImage;
                blog.BlogDate = p.BlogDate;
                var blogdetay = db.TblDetay.Where(x => x.BlogID == p.ID).FirstOrDefault();
                blogdetay.BlogImage1 = k.BlogImage1;
                blogdetay.BlogImage2 = k.BlogImage2;
                blogdetay.BlogComment1 = k.BlogComment1;
                blogdetay.BlogComment2 = k.BlogComment2;
                blogdetay.BlogSoz = k.BlogSoz;
                db.SaveChanges();
                return RedirectToAction("AdminAna");
            }
            catch (Exception a)
            {
                Response.Write("<script lang='JavaScript'>alert('" + a.Message + "');</script>");
                return View("AdminAna");
            }
        }
    }
}

Views/AdminPanel/Add.cshtml
<div style="margin-left:520px"><h1><u> BLOG EKLEME SAYFASI</u></h1></div>
@model ChessProject.Models.Entitiy.Tbl_Blog
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<br />
@using (Html.BeginForm("AddGo", "AdminPanel", FormMethod.Post))
{<label>BLOĞUN BAŞLIĞI:</label>
    <br />
    <div style="margin-left:10px">@Html.TextBoxFor(x => x.BlogTitle, new { @class = "form form-control", @required = "", @placeholder = "Blog Başlık Yazınız..", @MaxLength = 100 })</div>
    <br />
    <label>BLOG AÇIKLAMASI EN ÜSTTE:</label>
    <br />
    <div style="margin-left:10px">@Html.TextAreaFor(x => x.BlogComment, new { @class = "form form-control", @required = "", @placeholder = "Blog Açıklaması Yazınız..", @style = "height:100px", @minLength = "101" })</div>
    <br />
    <label>BLOG YAYIN TARİHİ:</label>
    <br />
    <div style="margin-left:10px">@Html.TextBoxFor(x => x.BlogDate, new { @class = "form form-control", @required = "", @Type = "date" })</div>
    <br />
    <label>BLOG RESİM EN BAŞTA GÖZÜKECEK (1920x1080px):</label>
    <br />
    <div style="margin-left:10px">@Html.TextBoxFor(x => x.BlogImage, new { @class = "form form-control", @required = "", @placeholder = "Blog Resim Link Yapıştırınız..", @MaxLength = 200 })</div>
    @Html.Action("BlogDetayAdd","AdminPanel")
    <button class="btn btn-info" type="submit">BLOG EKLE</button>
    <br />
    <br />
}

Views/AdminPanel/AdminAna.cshtml
<div style="margin-left:520px"><h1><u>BLOG SAYFASI</u></h1></div>
@model List<ChessProject.Models.Entitiy.Tbl_Blog>
@{
    ViewBag.Title = "AdminAna";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<br />
<table class="table table-hover" id="tbl1" border="1">
    <thead>
        <tr>
            <th>BAŞLIK</th>
            <th>TARİH</th>
            <th>İÇERİK</th>
            <th>RESİM</th>
            <th>GÜNCELLE</th>
            <th>SİL</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.BlogTitle</td>
                <td>
                    @item.BlogDate.ToShortDateString()
                </td>
                <td>@item.BlogComment.Substring(0,item.BlogComment.Substring(0,60).LastIndexOf(" "))...</td>
                <td>
                    <img src=" @item.BlogImage" width="70" height="70" alt="Blog Resim" />
                </td>
                <td>@Html.ActionLink("GÜNCELLE", "UpdatePage", new { id = item.ID }, new { @class = "btn btn-success" })</td>
                <td>@Html.ActionLink("SİL", "Delete", new { id = item.ID }, new { @class = "btn btn-danger", @onclick = "return confirm ('SİLMEK İSTEDİĞİNİZDEN EMİN MİSİNİZ ?')" })</td>
            </tr>
        }
    </tbody>
</table>
<a href="~/AdminPanel/Add/" class="btn btn-info">YENİ BLOG EKLE SAYFASI</a>
<br /><br />
<script>
    $('#tbl1').DataTable(
        {
            "language": {
                "url": "https://cdn.datatables.net/plug-ins/1.10.20/i18n/Turkish.json"
            }
        }
    );
</script>

Views/AdminPanel/BlogDetayAdd.cshtml
@model ChessProject.Models.Entitiy.TblDetay
<br />
<label>BLOG AÇIKLAMASI ORTA KISIM:</label>
<br />
<div style="margin-left:10px">@Html.TextAreaFor(x => x.BlogComment1, new { @class = "form form-control", @required = "", @placeholder = "Blog Açıklaması Yazınız..", @style = "height:100px", @minLength = "101" })</div>
<br />
<label>BLOG AÇIKLAMA EN ALTTA:</label>
<br />
<div style="margin-left:10px">@Html.TextAreaFor(x => x.BlogComment2, new { @class = "form form-control", @required = "", @placeholder = "Blog Açıklaması Yazınız..", @style = "height:100px", @minLength = "101" })</div>
<br />
<label>BLOG RESİM ORTA KISIMDA(1920x1080px)</label>
<br />
<div style="margin-left:10px">@Html.TextBoxFor(x => x.BlogImage1, new { @class = "form form-control", @required = "", @placeholder = "Blog Resim Link Yapıştırınız.."})</div>
<br />
<label>BLOG RESİM EN ALTTA(1920x1080px)</label>
<br />
<div style="margin-left:10px">@Html.TextBoxFor(x => x.BlogImage2, new { @class = "form form-control", @required = "", @placeholder = "Blog Resim Link Yapıştırınız.."})</div>
<br />
<label>BLOG SÖZ KISMI:</label>
<br />
<div style="margin-left:10px">@Html.TextBoxFor(x => x.BlogSoz, new { @class = "form form-control", @required = "", @placeholder = "Blog Söz Yazınız..", @MaxLength = 400 })</div>
<br />

Views/AdminPanel/BlogDetayUpdate.cshtml
@model ChessProject.Models.Entitiy.TblDetay
<br />
<label>BLOG AÇIKLAMASI ORTA KISIM:</label>
<br />
<div style="margin-left:10px">@Html.TextAreaFor(x => x.BlogComment1, new { @class = "form form-control", @required = "", @placeholder = "Blog Açıklaması Yazınız..", @style = "height:100px", @minLength = "101" })</div>
<br />
<label>BLOG AÇIKLAMA EN ALTTA:</label>
<br />
<div style="margin-left:10px">@Html.TextAreaFor(x => x.BlogComment2, new { @class = "form form-control", @required = "", @placeholder = "Blog Açıklaması Yazınız..", @style = "height:100px", @minLength = "101" })</div>
<br />
<label>BLOG RESİM ORTA KISIMDA(1920x1080px)</label>
<br />
<div style="margin-left:10px">@Html.TextBoxFor(x => x.BlogImage1, new { @class = "form form-control", @required = "", @placeholder = "Blog Resim Link Yapıştırınız.." })</div>
<br />
<label>BLOG RESİM EN ALTTA(1920x1080px)</label>
<br />
<div style="margin-left:10px">@Html.TextBoxFor(x => x.BlogImage2, new { @class = "form form-control", @required = "", @placeholder = "Blog Resim Link Yapıştırınız.." })</div>
<br />
<label>BLOG SÖZ KISMI:</label>
<br />
<div style="margin-left:10px">@Html.TextBoxFor(x => x.BlogSoz, new { @class = "form form-control", @required = "", @placeholder = "Blog Söz Yazınız..", @MaxLength = 400 })</div>
<br />

Views/AdminPanel/UpdatePage.cshtml
@model ChessProject.Models.Entitiy.Tbl_Blog
@{
    ViewBag.Title = "UpdatePage";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div style="margin-left:520px"><h1><u>BLOG GÜNCELLEME SAYFASI</u></h1></div>
<br />
<br />
@using (Html.BeginForm("UpdateGo", "AdminPanel", FormMethod.Post))
{
    <div style="margin-left:10px">@Html.TextBoxFor(x => x.ID, new { style = "display: none;" })</div>
    <label>BLOĞUN BAŞLIĞI:</label>
    <br />
    <div style="margin-left:10px">@Html.TextBoxFor(x => x.BlogTitle, new { @class = "form form-control", @required = "", @placeholder = "Blog Başlık Yazınız..", @MaxLength = 100 })</div>
    <br />
    <label>BLOG AÇIKLAMASI EN ÜSTTE:</label>
    <br />
    <div style="margin-left:10px">@Html.TextAreaFor(x => x.BlogComment, new { @class = "form form-control", @required = "", @placeholder = "Blog Açıklaması Yazınız..", @style = "height:100px", @minLength = "101" })</div>
    <br />
    <label>BLOG YAYIN TARİHİ:</label>
    <br />
    <div style="margin-left:10px">@Html.TextBoxFor(x => x.BlogDate, new { @class = "form form-control", @required = "", @Type = "date" })</div>
    <br />
    <label>BLOG RESİM EN BAŞTA GÖZÜKECEK (1920x1080px):</label>
    <br />
    <div style="margin-left:10px">@Html.TextBoxFor(x => x.BlogImage, new { @class = "form form-control", @required = "", @placeholder = "Blog Resim Link Yapıştırınız..", @MaxLength = 200 })</div>
    @Html.Action("BlogDetayUpdate", "AdminPanel")
    <button class="btn btn-info" type="submit">BLOG GÜNCELLE</button>
    <br />
    <br />
}